version: "3.8"
services:
  mongodb:
    image: mongo:8.0.0-rc8-jammy
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-volume:/data/db
volumes:
  mongo-volume:
